//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto copies the receiver into out.
func (in *PodGroup) DeepCopyInto(out *PodGroup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy creates a new copy of the receiver.
func (in *PodGroup) DeepCopy() *PodGroup {
	if in == nil {
		return nil
	}
	out := new(PodGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *PodGroup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies the receiver into out.
func (in *PodGroupList) DeepCopyInto(out *PodGroupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		l := make([]PodGroup, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&l[i])
		}
		out.Items = l
	}
}

// DeepCopy creates a new copy of the receiver.
func (in *PodGroupList) DeepCopy() *PodGroupList {
	if in == nil {
		return nil
	}
	out := new(PodGroupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *PodGroupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies the receiver into out.
func (in *PodGroupSpec) DeepCopyInto(out *PodGroupSpec) {
	*out = *in
	if in.ScheduleTimeoutSeconds != nil {
		v := *in.ScheduleTimeoutSeconds
		out.ScheduleTimeoutSeconds = &v
	}
	if in.MaxSchedulingBatch != nil {
		v := *in.MaxSchedulingBatch
		out.MaxSchedulingBatch = &v
	}
	if in.TopologyPolicy != nil {
		v := *in.TopologyPolicy
		out.TopologyPolicy = &v
	}
}

// DeepCopy creates a new copy of the receiver.
func (in *PodGroupSpec) DeepCopy() *PodGroupSpec {
	if in == nil {
		return nil
	}
	out := new(PodGroupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *PodGroupStatus) DeepCopyInto(out *PodGroupStatus) {
	*out = *in
	if in.Conditions != nil {
		l := make([]PodGroupCondition, len(in.Conditions))
		for i := range in.Conditions {
			in.Conditions[i].DeepCopyInto(&l[i])
		}
		out.Conditions = l
	}
	if in.LastScheduleTime != nil {
		v := *in.LastScheduleTime
		out.LastScheduleTime = &v
	}
}

// DeepCopy creates a new copy of the receiver.
func (in *PodGroupStatus) DeepCopy() *PodGroupStatus {
	if in == nil {
		return nil
	}
	out := new(PodGroupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *PodGroupCondition) DeepCopyInto(out *PodGroupCondition) {
	*out = *in
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
}

// DeepCopy creates a new copy of the receiver.
func (in *PodGroupCondition) DeepCopy() *PodGroupCondition {
	if in == nil {
		return nil
	}
	out := new(PodGroupCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *TopologyPolicy) DeepCopyInto(out *TopologyPolicy) {
	*out = *in
}

// DeepCopy creates a new copy of the receiver.
func (in *TopologyPolicy) DeepCopy() *TopologyPolicy {
	if in == nil {
		return nil
	}
	out := new(TopologyPolicy)
	in.DeepCopyInto(out)
	return out
}
