//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto copies the receiver into out.
func (in *NodeGpuTopology) DeepCopyInto(out *NodeGpuTopology) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy creates a new copy of the receiver.
func (in *NodeGpuTopology) DeepCopy() *NodeGpuTopology {
	if in == nil {
		return nil
	}
	out := new(NodeGpuTopology)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *NodeGpuTopology) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies the receiver into out.
func (in *NodeGpuTopologyList) DeepCopyInto(out *NodeGpuTopologyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		l := make([]NodeGpuTopology, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&l[i])
		}
		out.Items = l
	}
}

// DeepCopy creates a new copy of the receiver.
func (in *NodeGpuTopologyList) DeepCopy() *NodeGpuTopologyList {
	if in == nil {
		return nil
	}
	out := new(NodeGpuTopologyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *NodeGpuTopologyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies the receiver into out.
func (in *NodeGpuTopologySpec) DeepCopyInto(out *NodeGpuTopologySpec) {
	*out = *in
	if in.Gpus != nil {
		l := make([]Gpu, len(in.Gpus))
		for i := range in.Gpus {
			in.Gpus[i].DeepCopyInto(&l[i])
		}
		out.Gpus = l
	}
	if in.Domains != nil {
		l := make([]Domain, len(in.Domains))
		for i := range in.Domains {
			in.Domains[i].DeepCopyInto(&l[i])
		}
		out.Domains = l
	}
}

// DeepCopy creates a new copy of the receiver.
func (in *NodeGpuTopologySpec) DeepCopy() *NodeGpuTopologySpec {
	if in == nil {
		return nil
	}
	out := new(NodeGpuTopologySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *Gpu) DeepCopyInto(out *Gpu) {
	*out = *in
	if in.AllocatedTo != nil {
		v := *in.AllocatedTo
		out.AllocatedTo = &v
	}
	if in.Peers != nil {
		l := make([]GpuPeer, len(in.Peers))
		copy(l, in.Peers)
		out.Peers = l
	}
}

// DeepCopy creates a new copy of the receiver.
func (in *Gpu) DeepCopy() *Gpu {
	if in == nil {
		return nil
	}
	out := new(Gpu)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *GpuAllocation) DeepCopyInto(out *GpuAllocation) {
	*out = *in
}

// DeepCopy creates a new copy of the receiver.
func (in *GpuAllocation) DeepCopy() *GpuAllocation {
	if in == nil {
		return nil
	}
	out := new(GpuAllocation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *GpuPeer) DeepCopyInto(out *GpuPeer) {
	*out = *in
}

// DeepCopy creates a new copy of the receiver.
func (in *GpuPeer) DeepCopy() *GpuPeer {
	if in == nil {
		return nil
	}
	out := new(GpuPeer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *Domain) DeepCopyInto(out *Domain) {
	*out = *in
	if in.GpuIndexes != nil {
		l := make([]int32, len(in.GpuIndexes))
		copy(l, in.GpuIndexes)
		out.GpuIndexes = l
	}
}

// DeepCopy creates a new copy of the receiver.
func (in *Domain) DeepCopy() *Domain {
	if in == nil {
		return nil
	}
	out := new(Domain)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *NodeGpuTopologyStatus) DeepCopyInto(out *NodeGpuTopologyStatus) {
	*out = *in
	if in.LastHeartbeat != nil {
		v := *in.LastHeartbeat
		out.LastHeartbeat = &v
	}
	if in.Healthy != nil {
		v := *in.Healthy
		out.Healthy = &v
	}
}

// DeepCopy creates a new copy of the receiver.
func (in *NodeGpuTopologyStatus) DeepCopy() *NodeGpuTopologyStatus {
	if in == nil {
		return nil
	}
	out := new(NodeGpuTopologyStatus)
	in.DeepCopyInto(out)
	return out
}
